Compatibility with new laravel version 6.0
bissolli/nova-phone-field pull request #4
Opened 2019-09-04 14:25 UTC by nibri10

In new versions of laravel nova there is no longer the array_flatten that was replaced by Arr :: flatten and now it is necessary to import the class use Illuminate \ Support \ Arr; for the project to work on laravel version 6.0 and other versions.

2019-09-05 07:07 UTC, bissolli requested changes
Thanks for the support @nibri10! 
Just a small adjust to be compliance with our StyleCI.

2019-09-05 07:07 UTC, bissolli commented on src/PhoneNumber.php
> +use Illuminate\Support\Arr;
Can you break like here so it will pass through our StyleCI?

```suggestion
use Illuminate\Support\Arr;

```

2019-09-05 11:49 UTC, nibri10 commented
> Thanks for the support @nibri10!
> Just a small adjust to be compliance with our StyleCI.

Resolve

2019-09-07 13:48 UTC, nibri10 commented
@bissolli

2019-09-08 06:00 UTC, merged